name: Build JSON hourly

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLAYLIST_URL: ${{ secrets.PLAYLIST_URL }}
      PLAYLIST_REFERER: ${{ secrets.PLAYLIST_REFERER }}
      PLAYLIST_ORIGIN: ${{ secrets.PLAYLIST_ORIGIN }}
      TARGET_REPO: ${{ secrets.TARGET_REPO }}        # e.g. your-org/target-repo
      TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}      # PAT with repo permissions
      TARGET_BRANCH: ${{ secrets.TARGET_BRANCH }}    # e.g. master (default)
      TARGET_DIR: ${{ secrets.TARGET_DIR }}          # subdir in target repo, e.g. public or . (optional)
      CODE_REPO: ${{ secrets.CODE_REPO }}            # e.g. your-org/ayna-tv-fetch (the repo that has the CLI code)
      CODE_REF: ${{ secrets.CODE_REF }}              # branch/tag of code repo (default: master)
      FILTER_PATH: ${{ secrets.FILTER_PATH }}        # optional path to filter file; defaults to code-repo/src/filter.js
      CODE_TOKEN: ${{ secrets.CODE_TOKEN }}          # PAT with repo:read for CODE_REPO (private)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate secrets for code repo access
        if: env.CODE_REPO != '' && env.CODE_TOKEN == ''
        shell: bash
        run: |
          echo "CODE_REPO is set to '${CODE_REPO}', but CODE_TOKEN is empty." >&2
          echo "Provide a PAT with Contents: Read for the code repo (private repos require it)." >&2
          exit 1

      - name: Checkout code repo (CLI)
        if: env.CODE_REPO != ''
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CODE_REPO }}
          ref: ${{ env.CODE_REF || 'master' }}
          token: ${{ env.CODE_TOKEN }}
          path: code-repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (code repo)
        run: |
          set -euo pipefail
          if [ -d code-repo ]; then
            cd code-repo
            if [ -f package.json ]; then npm ci || npm install; fi
          else
            if [ -f package.json ]; then npm ci || npm install; fi
          fi

      - name: Build JSON files
        shell: bash
        run: |
          set -euo pipefail
          if [[ -z "${PLAYLIST_URL:-}" ]]; then
            echo "PLAYLIST_URL secret is not set. Please add it in repo settings > Secrets and variables > Actions." >&2
            exit 1
          fi
          REFERER_ARG=""
          ORIGIN_ARG=""
          if [[ -n "${PLAYLIST_REFERER:-}" ]]; then REFERER_ARG=(--referer "$PLAYLIST_REFERER"); fi
          if [[ -n "${PLAYLIST_ORIGIN:-}" ]]; then ORIGIN_ARG=(--origin "$PLAYLIST_ORIGIN"); fi
          mkdir -p output
          if [[ -d code-repo ]]; then
            FILTER_ARG=(--filter "${FILTER_PATH:-code-repo/src/filter.js}")
            node code-repo/bin/m3u-to-json.js --url "$PLAYLIST_URL" "${REFERER_ARG[@]}" "${ORIGIN_ARG[@]}" "${FILTER_ARG[@]}" --write-both --out-dir output --out api.json --out-filter filtered.json
          else
            # fallback: CLI is in this repo
            node bin/m3u-to-json.js --url "$PLAYLIST_URL" "${REFERER_ARG[@]}" "${ORIGIN_ARG[@]}" --filter src/filter.js --write-both --out-dir output --out api.json --out-filter filtered.json
          fi

      - name: Validate secrets for target repo access
        if: env.TARGET_REPO != '' && env.TARGET_TOKEN == ''
        shell: bash
        run: |
          echo "TARGET_REPO is set to '${TARGET_REPO}', but TARGET_TOKEN is empty." >&2
          echo "Provide a PAT with Contents: Read/Write for the target repo to enable pushing." >&2
          exit 1

      - name: Debug target push condition
        shell: bash
        run: |
          echo "TARGET_REPO='${TARGET_REPO:-}'"
          if [[ -n "${TARGET_REPO:-}" && -n "${TARGET_TOKEN:-}" ]]; then
            echo "Push to target repo will run."
          else
            echo "Push to target repo will be skipped (missing TARGET_REPO or TARGET_TOKEN)."
          fi

      - name: Push artifacts to external private repo
        if: env.TARGET_REPO != '' && env.TARGET_TOKEN != ''
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          token: ${{ env.TARGET_TOKEN }}
          ref: ${{ env.TARGET_BRANCH || 'master' }}
          path: target-repo

      - name: Copy artifacts into target repo and push
        if: env.TARGET_REPO != '' && env.TARGET_TOKEN != ''
        shell: bash
        run: |
          set -euo pipefail
          DEST_DIR="target-repo/${TARGET_DIR:-.}"
          mkdir -p "$DEST_DIR"
          cp -f output/api.json "$DEST_DIR/"
          cp -f output/filtered.json "$DEST_DIR/"
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update api.json and filtered.json (external)" || echo "No changes to commit"
          git push

      # Removed local commit step to prevent writing outputs to auto-update repo

